### ISSUE TITLE
Mount controller sets the password to the same value as the username

### ISSUE THREAD

**Issue by nrledo** [openshift-telco/netconf-operator#3]
Hi, 
Sorry if this is not maintained anymore, but I was testing the controller for a project I'm working in and came across this bug. 

When installing the controller, and setting a correct user name and password, I would get the message:

manager 2024-08-22T15:07:08.984Z DEBUG controller-runtime.manager.events Warning {"object": {"kind":"MountPoint","namespace":"netconf-operator","name":"netconf-server","uid":"41f83a04-4cb5-4c6f-95ca-36488edbdd60","api Version":"netconf.openshift-telco.io/v1","resourceVersion":"338240900"}, "reason": "ProcessingError", "message": "ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain"} manager 2024-08-22T15:07:08.996Z ERROR controller-runtime.manager.controller.mountpoint Reconciler error {"name": "netconf-server", "namespace": "netconf-operator", "error": "ssh: handshake failed: ssh: unable to auth enticate, attempted methods [none password], no supported methods remain"}

Checking the code, I realized there's a typo and I submitted a pull request to fix it:
https://github.com/openshift-telco/netconf-operator/pull/2

**Comment by adetalhouet** [comment]
fixed https://github.com/openshift-telco/netconf-operator/pull/2

**Comment by adetalhouet** [comment]
Thanks @nrledo
